language: node_js
node_js:
  - "4"
  - "5"
  - "6"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "6"
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.11.8 && cat ./coverage/lcov.info | coveralls"
addons:
  postgresql: "9.4"
before_script:
  - psql < ./test/setup/create_test_db.sql
  - psql < ./test/setup/create_comun_schema.sql
  - cp travis-test-config.yaml local-test-config.yaml
